### PR TITLE
Example of fix with docker networking

### PR DESCRIPTION
**Pull request by ryansonshine**

### CODE REVIEW

**Comment by jgomes94** [comment]
Thank you so much @ryansonshine !!! 

You have no idea for how long I was struggling with this and it never ocurred to me that it could be an issue with docker itself. @ryansonshine I would like to pay you a beer as a thank you.. if you could provide me your paypal email I will be able to send it. If you prefer you can contact me on  https://www.linkedin.com/in/gomes-joao/ and provide me with the details there.

Again, thank you very much! 👍

**Comment by ryansonshine** [comment]
Happy to help and thank you for your offer; please route that beer money over to the EFF https://supporters.eff.org/donate/30for30--D 😄

**Comment by jgomes94** [comment]
Will do @ryansonshine ! 👍 BTW, do you have some recommendation for resources to go deeper into docker? I clearly lack knowledge in this field and some learning couldn't hurt 👍

**Comment by ryansonshine** [comment]
I personally think Pluralsight is a pretty good resource although it's not all free. https://www.pluralsight.com/courses/getting-started-docker

**Pull request merged**
